spring.application.name=rca-backend

spring.config.import=optional:file:.env[.properties]

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.model.chat=openai
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.embedding=none
spring.ai.model.image=none
spring.ai.model.moderation=none

pinecone.api-key=${PINECONE_API_KEY}
pinecone.index-host=${PINECONE_INDEX_HOST}
pinecone.namespace=${PINECONE_NAMESPACE}
pinecone.api-version=2025-10
pinecone.top-k=2



dashboard.logs-file=C:/Users/saito/source/repos/AIEngineering_JavaPython/AI-Banking-Logs-RCA-Agent/RAG-Ingestion/data/raw_logs.jsonl